In [1]:
import numpy as np
# function for Alexandre-Theophile Vandermonde.

def vander(arr,boolean):
    N= len(arr)
    if boolean == False:
        print(np.column_stack([arr**(N-1-i) for i in range(N)]))
    elif boolean ==True:
        print(np.column_stack([arr**(N-1-i) for i in range(N-1,-1,-1)]))

In [2]:
# Output in increasing order
lst=[1,2,3,4,5,6]
arr=np.array(lst)
vander(arr,True)

[[   1    1    1    1    1    1]
 [   1    2    4    8   16   32]
 [   1    3    9   27   81  243]
 [   1    4   16   64  256 1024]
 [   1    5   25  125  625 3125]
 [   1    6   36  216 1296 7776]]


In [3]:
#output in decreasing order
lst=[1,2,3,4,5,6]
arr=np.array(lst)
vander(arr,False)

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]]


Moving Average

In [4]:
#Function for moving average
lst_t =[]
def mov_avg(lst,k):
    n=0
    N =len(lst)
    z=k
    iter = N-k+1
    for i in range (iter):
        lst_t = lst[n:k]
        print("Moving average ",i+1," :",sum(lst_t)/z )
        n=n+1
        k=k+1
    

In [5]:
lst=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
mov_avg(lst,3)

Moving average  1  : 5.0
Moving average  2  : 4.666666666666667
Moving average  3  : 5.666666666666667
Moving average  4  : 6.666666666666667
Moving average  5  : 9.666666666666666
Moving average  6  : 28.666666666666668
Moving average  7  : 49.333333333333336
Moving average  8  : 72.66666666666667
Moving average  9  : 84.0
Moving average  10  : 93.33333333333333
Moving average  11  : 116.33333333333333
